sudo: required
services:
    - docker


before_install:
    - docker build -t waytkheming/cicd-sample -f Dockerfile.dev .

script:
    - docker run -e CI=true waytkheming/cicd-sample npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-1"
    app: "dokcer"
    env: "Dokcer-env"
    bucket_name: "elasticbeanstalk-ap-northeast-1-431294835211"
    bucket_path: "dokcer"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"